definitions:
  request.LoginRequest:
    properties:
      email:
        type: string
        x-order: "0"
      password:
        example: password
        type: string
        x-order: "1"
    required:
    - email
    - password
    type: object
  request.RegisterRequest:
    properties:
      email:
        type: string
        x-order: "1"
      password:
        example: password
        minLength: 8
        type: string
        x-order: "2"
      username:
        maxLength: 20
        minLength: 3
        type: string
        x-order: "0"
    required:
    - email
    - password
    - username
    type: object
  request.TransactionCreate:
    properties:
      bikeId:
        type: integer
      quantity:
        type: integer
      totalPrice:
        type: integer
    type: object
  request.TransactionUpdate:
    properties:
      bikeId:
        type: integer
      id:
        type: integer
      quantity:
        type: integer
      totalPrice:
        type: integer
    type: object
  response.LoginResponse:
    properties:
      email:
        example: luigi@sam.com
        type: string
        x-order: "1"
      role:
        example: USER
        type: string
        x-order: "2"
      token:
        example: token
        type: string
        x-order: "3"
      username:
        example: luigi
        type: string
        x-order: "0"
    type: object
  response.OrderResponse:
    properties:
      bikeID:
        type: integer
      id:
        type: integer
      quantity:
        type: integer
      totalPrice:
        type: integer
    type: object
  response.RegisterResponse:
    properties:
      email:
        example: luigi@sam.com
        type: string
        x-order: "1"
      role:
        example: USER
        type: string
        x-order: "2"
      username:
        example: luigi
        type: string
        x-order: "0"
    type: object
  response.TransactionResponse:
    properties:
      autoCreateTime:
        type: string
      autoUpdateTime:
        type: string
      id:
        type: integer
      orders:
        items:
          $ref: '#/definitions/response.OrderResponse'
        type: array
      status:
        type: string
      totalPrice:
        type: integer
      userId:
        type: integer
    type: object
  web.Metadata:
    properties:
      limit:
        type: integer
        x-order: "1"
      page:
        type: integer
        x-order: "0"
      total_data:
        type: integer
        x-order: "3"
      total_pages:
        type: integer
        x-order: "2"
    type: object
  web.WebBadRequestError:
    properties:
      code:
        example: 400
        type: integer
      errors:
        example: Bad Request
        type: string
    type: object
  web.WebInternalServerError:
    properties:
      code:
        example: 500
        type: integer
      errors:
        example: Internal Server Error
        type: string
    type: object
  web.WebSuccess-array_response_TransactionResponse:
    properties:
      code:
        example: 200
        type: integer
        x-order: "0"
      message:
        example: success
        type: string
        x-order: "1"
      metadata:
        allOf:
        - $ref: '#/definitions/web.Metadata'
        x-order: "3"
      payload:
        items:
          $ref: '#/definitions/response.TransactionResponse'
        type: array
        x-order: "2"
    type: object
  web.WebSuccess-response_LoginResponse:
    properties:
      code:
        example: 200
        type: integer
        x-order: "0"
      message:
        example: success
        type: string
        x-order: "1"
      metadata:
        allOf:
        - $ref: '#/definitions/web.Metadata'
        x-order: "3"
      payload:
        allOf:
        - $ref: '#/definitions/response.LoginResponse'
        x-order: "2"
    type: object
  web.WebSuccess-response_RegisterResponse:
    properties:
      code:
        example: 200
        type: integer
        x-order: "0"
      message:
        example: success
        type: string
        x-order: "1"
      metadata:
        allOf:
        - $ref: '#/definitions/web.Metadata'
        x-order: "3"
      payload:
        allOf:
        - $ref: '#/definitions/response.RegisterResponse'
        x-order: "2"
    type: object
  web.WebSuccess-response_TransactionResponse:
    properties:
      code:
        example: 200
        type: integer
        x-order: "0"
      message:
        example: success
        type: string
        x-order: "1"
      metadata:
        allOf:
        - $ref: '#/definitions/web.Metadata'
        x-order: "3"
      payload:
        allOf:
        - $ref: '#/definitions/response.TransactionResponse'
        x-order: "2"
    type: object
  web.WebSuccess-string:
    properties:
      code:
        example: 200
        type: integer
        x-order: "0"
      message:
        example: success
        type: string
        x-order: "1"
      metadata:
        allOf:
        - $ref: '#/definitions/web.Metadata'
        x-order: "3"
      payload:
        type: string
        x-order: "2"
    type: object
  web.WebUnauthorizedError:
    properties:
      code:
        example: 401
        type: integer
      errors:
        example: Unauthorized
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/login:
    post:
      description: Logging in to get jwt token to access admin or user api by roles.
      parameters:
      - description: the body to login a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-response_LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.WebUnauthorizedError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: User login.
      tags:
      - Auth
  /api/auth/register:
    post:
      description: Registering a user from public access.
      parameters:
      - description: the body to register a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.WebSuccess-response_RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: User register.
      tags:
      - Auth
  /api/transactions:
    get:
      description: Registering a user from public access.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-array_response_TransactionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: Get all transaction.
      tags:
      - Transactions
  /api/transactions/{id}:
    delete:
      description: Delete a transaction
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: Delete a transaction
      tags:
      - Transactions
    get:
      description: Get transaction by ID
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-response_TransactionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: Get transaction by ID
      tags:
      - Transactions
    patch:
      consumes:
      - application/json
      description: Update a transaction
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      - description: Transaction update payload
        in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/request.TransactionUpdate'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: Update a transaction
      tags:
      - Transactions
  /api/transactions/{userId}:
    post:
      consumes:
      - application/json
      description: Create a new transaction
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      - description: Transaction payload
        in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/request.TransactionCreate'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: Create a new transaction
      tags:
      - Transactions
  /api/transactions/payment/{id}:
    patch:
      description: Pay for a transaction
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: Pay for a transaction
      tags:
      - Transactions
swagger: "2.0"
