definitions:
  request.ForgotPasswordRequest:
    properties:
      email:
        type: string
      username:
        maxLength: 20
        minLength: 3
        type: string
        x-order: "0"
    required:
    - email
    - username
    type: object
  request.LoginRequest:
    properties:
      email:
        type: string
        x-order: "0"
      password:
        example: password
        type: string
        x-order: "1"
    required:
    - email
    - password
    type: object
  request.RegisterRequest:
    properties:
      email:
        type: string
        x-order: "1"
      password:
        example: password
        minLength: 8
        type: string
        x-order: "2"
      username:
        maxLength: 20
        minLength: 3
        type: string
        x-order: "0"
    required:
    - email
    - password
    - username
    type: object
  request.ResetPasswordRequest:
    properties:
      new_password:
        example: new_password
        minLength: 8
        type: string
        x-order: "1"
      token:
        example: token
        type: string
        x-order: "0"
    required:
    - new_password
    - token
    type: object
  request.UpdatePasswordRequest:
    properties:
      password:
        minLength: 3
        type: string
    required:
    - password
    type: object
  request.UpdateUserProfileRequest:
    properties:
      age:
        minimum: 0
        type: integer
        x-order: "4"
      bio:
        maxLength: 500
        type: string
        x-order: "3"
      email:
        type: string
        x-order: "1"
      full_name:
        maxLength: 100
        minLength: 3
        type: string
        x-order: "2"
      gender:
        enum:
        - MALE
        - FEMALE
        type: string
        x-order: "5"
      username:
        maxLength: 20
        minLength: 3
        type: string
        x-order: "0"
    type: object
  response.ForgotPasswordResponse:
    properties:
      token:
        example: token
        type: string
    type: object
  response.GetUserCurrentResponse:
    properties:
      email:
        example: luigi@sam.com
        type: string
        x-order: "3"
      id:
        example: 1
        type: integer
        x-order: "0"
      role:
        example: USER
        type: string
        x-order: "4"
      username:
        example: luigi
        type: string
        x-order: "2"
    type: object
  response.LoginResponse:
    properties:
      email:
        example: luigi@sam.com
        type: string
        x-order: "1"
      role:
        example: USER
        type: string
        x-order: "2"
      token:
        example: token
        type: string
        x-order: "3"
      username:
        example: luigi
        type: string
        x-order: "0"
    type: object
  response.RegisterResponse:
    properties:
      email:
        example: luigi@sam.com
        type: string
        x-order: "1"
      role:
        example: USER
        type: string
        x-order: "2"
      username:
        example: luigi
        type: string
        x-order: "0"
    type: object
  response.UpdateUserProfileResponse:
    properties:
      age:
        example: 18
        type: integer
        x-order: "6"
      bio:
        example: I am Luigi
        type: string
        x-order: "5"
      email:
        example: luigi@sam.com
        type: string
        x-order: "3"
      full_name:
        example: Luigi Di Caprio
        type: string
        x-order: "4"
      gender:
        example: MALE
        type: string
        x-order: "7"
      id:
        example: 1
        type: integer
        x-order: "0"
      role:
        example: USER
        type: string
        x-order: "2"
      username:
        example: luigi
        type: string
        x-order: "1"
    type: object
  response.UserProfileResponse:
    properties:
      age:
        example: 18
        type: integer
        x-order: "6"
      bio:
        example: I am Luigi
        type: string
        x-order: "5"
      email:
        example: luigi@sam.com
        type: string
        x-order: "3"
      full_name:
        example: Luigi Di Caprio
        type: string
        x-order: "4"
      gender:
        example: MALE
        type: string
        x-order: "7"
      id:
        example: 1
        type: integer
        x-order: "0"
      role:
        example: USER
        type: string
        x-order: "2"
      username:
        example: luigi
        type: string
        x-order: "1"
    type: object
  web.Metadata:
    properties:
      limit:
        type: integer
        x-order: "1"
      page:
        type: integer
        x-order: "0"
      total_data:
        type: integer
        x-order: "3"
      total_pages:
        type: integer
        x-order: "2"
    type: object
  web.WebBadRequestError:
    properties:
      code:
        example: 400
        type: integer
      errors:
        example: Bad Request
        type: string
    type: object
  web.WebInternalServerError:
    properties:
      code:
        example: 500
        type: integer
      errors:
        example: Internal Server Error
        type: string
    type: object
  web.WebNotFoundError:
    properties:
      code:
        example: 404
        type: integer
      errors:
        example: Not Found
        type: string
    type: object
  web.WebSuccess-response_ForgotPasswordResponse:
    properties:
      code:
        example: 200
        type: integer
        x-order: "0"
      message:
        example: success
        type: string
        x-order: "1"
      metadata:
        allOf:
        - $ref: '#/definitions/web.Metadata'
        x-order: "3"
      payload:
        allOf:
        - $ref: '#/definitions/response.ForgotPasswordResponse'
        x-order: "2"
    type: object
  web.WebSuccess-response_GetUserCurrentResponse:
    properties:
      code:
        example: 200
        type: integer
        x-order: "0"
      message:
        example: success
        type: string
        x-order: "1"
      metadata:
        allOf:
        - $ref: '#/definitions/web.Metadata'
        x-order: "3"
      payload:
        allOf:
        - $ref: '#/definitions/response.GetUserCurrentResponse'
        x-order: "2"
    type: object
  web.WebSuccess-response_LoginResponse:
    properties:
      code:
        example: 200
        type: integer
        x-order: "0"
      message:
        example: success
        type: string
        x-order: "1"
      metadata:
        allOf:
        - $ref: '#/definitions/web.Metadata'
        x-order: "3"
      payload:
        allOf:
        - $ref: '#/definitions/response.LoginResponse'
        x-order: "2"
    type: object
  web.WebSuccess-response_RegisterResponse:
    properties:
      code:
        example: 200
        type: integer
        x-order: "0"
      message:
        example: success
        type: string
        x-order: "1"
      metadata:
        allOf:
        - $ref: '#/definitions/web.Metadata'
        x-order: "3"
      payload:
        allOf:
        - $ref: '#/definitions/response.RegisterResponse'
        x-order: "2"
    type: object
  web.WebSuccess-response_UpdateUserProfileResponse:
    properties:
      code:
        example: 200
        type: integer
        x-order: "0"
      message:
        example: success
        type: string
        x-order: "1"
      metadata:
        allOf:
        - $ref: '#/definitions/web.Metadata'
        x-order: "3"
      payload:
        allOf:
        - $ref: '#/definitions/response.UpdateUserProfileResponse'
        x-order: "2"
    type: object
  web.WebSuccess-response_UserProfileResponse:
    properties:
      code:
        example: 200
        type: integer
        x-order: "0"
      message:
        example: success
        type: string
        x-order: "1"
      metadata:
        allOf:
        - $ref: '#/definitions/web.Metadata'
        x-order: "3"
      payload:
        allOf:
        - $ref: '#/definitions/response.UserProfileResponse'
        x-order: "2"
    type: object
  web.WebSuccess-string:
    properties:
      code:
        example: 200
        type: integer
        x-order: "0"
      message:
        example: success
        type: string
        x-order: "1"
      metadata:
        allOf:
        - $ref: '#/definitions/web.Metadata'
        x-order: "3"
      payload:
        type: string
        x-order: "2"
    type: object
  web.WebUnauthorizedError:
    properties:
      code:
        example: 401
        type: integer
      errors:
        example: Unauthorized
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/forgot-password:
    post:
      description: Request forgot password.
      parameters:
      - description: the body to request forgot password
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/request.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-response_ForgotPasswordResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.WebNotFoundError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: Forgot password.
      tags:
      - Auth
  /api/auth/login:
    post:
      description: Logging in to get jwt token to access admin or user api by roles.
      parameters:
      - description: the body to login a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-response_LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.WebUnauthorizedError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: User login.
      tags:
      - Auth
  /api/auth/register:
    post:
      description: Registering a user from public access.
      parameters:
      - description: the body to register a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.WebSuccess-response_RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: User register.
      tags:
      - Auth
  /api/auth/reset-password:
    post:
      description: Reset password.
      parameters:
      - description: the body to reset password
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/request.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.WebNotFoundError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: Reset password.
      tags:
      - Auth
  /api/users:
    delete:
      description: Delete a user profile by ID.
      parameters:
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      security:
      - BearerToken: []
      summary: Delete user.
      tags:
      - Users
  /api/users/current:
    get:
      description: Get current user.
      parameters:
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-response_GetUserCurrentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.WebNotFoundError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      security:
      - BearerToken: []
      summary: Get current user.
      tags:
      - Users
  /api/users/password:
    patch:
      description: Update the current user's password.
      parameters:
      - description: the body to update a password
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/request.UpdatePasswordRequest'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      security:
      - BearerToken: []
      summary: Update user password.
      tags:
      - Users
  /api/users/profile:
    patch:
      description: Update the profile of a user.
      parameters:
      - description: the body to update user profile
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/request.UpdateUserProfileRequest'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-response_UpdateUserProfileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      security:
      - BearerToken: []
      summary: Update user profile.
      tags:
      - Users
  /api/users/profile/{id}:
    get:
      description: Get user profile data.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebSuccess-response_UserProfileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebBadRequestError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.WebNotFoundError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebInternalServerError'
      summary: Get user profile.
      tags:
      - Users
swagger: "2.0"
